version: "3.8"

services:
  backend:
    build: ./Notes-BE
    ports:
      - "3000:3000"
    env_file:
      - ./Notes-BE/.env
  frontend:
    build: ./Notes
    ports:
      - "5173:80"
    depends_on:
      - backend
